// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Lagomoro_Mission","status":false,"description":"Lagomoro任务系统 版本：V13.1.0 正式版","parameters":{"数据库存储路径":"data/Lagomoro_Mission.xlsx","是否推送任务信息":"true","困难度文字列表":"[\"简单\",\"一般\",\"中等\",\"困难\",\"超困难！\"]","任务菜单设置":"","上边距":"20","下边距":"20","左边距":"50","右边距":"50","章节列表宽度":"240","菜单显示名称":"任务","地图任务窗口设置":"","左右位置初始状态":"true","上下位置初始状态":"5","窗口宽度":"260","窗口背景颜色":"rgba(0,0,0,0.4)","系统皮肤透明度":"0"}}
];
